name: tntm_reproduce
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch==2.1.0     # or your CUDA-specific build
      - transformers==4.52.4
      - sentence-transformers==2.7.0
      - octis==1.14.0
      - umap-learn==0.5.7
      - pandas==1.5.3
      - gensim==4.3.3
      - scikit-learn==1.1.0
      - tqdm==4.67.1
      - matplotlib==3.9.4
      - nltk==3.9.1
      - hdbscan==0.8.40
      - topmost==1.0.1
